server:
  port: 7070


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kiohunter12/sisventaslibros.git
          searchPaths: config-data
          #username:
          #password:
          default-label: main
  security:
    user:
      password: 123456
      name: root